theme: jekyll-theme-minimal
title: HiThink-Nexus-Humanoid's homepage
description: Bookmark this to keep an eye on my project updates!
lang: en

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock